class CreateSpells < ActiveRecord::Migration
  def change
    create_table :spells do |t|
      t.string :name
      t.string :school
      t.string :subschool
      t.string :descriptor
      t.string :spell_level
      t.string :casting_time
      t.string :components
      t.boolean :costly_components
      t.string :range
      t.string :area
      t.string :effect
      t.string :targets
      t.string :duration
      t.boolean :dismissible
      t.boolean :shapeable
      t.string :saving_throw
      t.string :spell_resistence
      t.string :description
      t.string :description_formated
      t.string :source
      t.string :full_text
      t.boolean :verbal
      t.boolean :somatic
      t.boolean :material
      t.boolean :focus
      t.boolean :divine_focus
      t.string :sor
      t.string :wiz
      t.string :cleric
      t.string :druid
      t.string :ranger
      t.string :bard
      t.string :paladin
      t.string :alchemist
      t.string :summoner
      t.string :witch
      t.string :inquisitor
      t.string :oracle
      t.string :antipaladin
      t.string :magus
      t.string :adept
      t.string :deity
      t.string :SLA_Level
      t.string :domain
      t.string :short_description
      t.boolean :acid
      t.boolean :air
      t.boolean :chaotic
      t.boolean :cold
      t.boolean :curse
      t.boolean :darkness
      t.boolean :death
      t.boolean :disease
      t.boolean :earth
      t.boolean :electricity
      t.boolean :emotion
      t.boolean :evil
      t.boolean :fear
      t.boolean :fire
      t.boolean :force
      t.boolean :good
      t.boolean :language_dependent
      t.boolean :lawful
      t.boolean :light
      t.boolean :mind_affecting
      t.boolean :pain
      t.boolean :poison
      t.boolean :shadow
      t.boolean :sonic
      t.boolean :water
      t.string :linktext
      t.string :material_costs
      t.string :bloodline
      t.string :patron
      t.string :mythic_text
      t.string :augmented
      t.boolean :mythic
      t.string :bloodrager
      t.string :shaman
      t.string :psychic
      t.string :medium
      t.string :mesmerist
      t.string :occultist
      t.string :spiritualist
      t.string :skald

      t.timestamps null: false
    end
  end
end
